{% extends "base.phtml" %}

{% block content %}
<div class="row">
	<div class="col-md-8 col-md-offset-2 table-responsive" style="text-align:center;">
		<h4>Cart</h4>
		<p>A table highlighting the products in the cart</p>
		<table class="table table-striped">
			<thead>
			<tr><th>Product Name</th><th>Quantity</th></tr>
			</thead>
			<tbody>
			<?php
			// Generate Cart Reports
			?>
			</tbody>
		</table>
	
	</div>
</div>
{% endblock %}